/**
 *  Copyright (c) 2019 CentraleSupélec & EDF.
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  which accompanies this distribution, and is available at
 *  http://www.eclipse.org/legal/epl-v10.html
 * 
 *  This file is part of the RiseClipse tool
 *  
 *  Contributors:
 *      Computer Science Department, CentraleSupélec
 *      EDF R&D
 *  Contacts:
 *      dominique.marcadet@centralesupelec.fr
 *      aurelie.dehouck-neveu@edf.fr
 *  Web site:
 *      http://wdi.supelec.fr/software/RiseClipse/
 * 
 */
package fr.centralesupelec.edf.riseclipse.iec61850.nsd.provider;

import fr.centralesupelec.edf.riseclipse.iec61850.nsd.util.NsdAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class NsdItemProviderAdapterFactory extends NsdAdapterFactory
        implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
    /**
     * This keeps track of the root adapter factory that delegates to this adapter factory.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ComposedAdapterFactory parentAdapterFactory;

    /**
     * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected IChangeNotifier changeNotifier = new ChangeNotifier();

    /**
     * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected Collection< Object > supportedTypes = new ArrayList< Object >();

    /**
     * This constructs an instance.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public NsdItemProviderAdapterFactory() {
        supportedTypes.add( IEditingDomainItemProvider.class );
        supportedTypes.add( IStructuredItemContentProvider.class );
        supportedTypes.add( ITreeItemContentProvider.class );
        supportedTypes.add( IItemLabelProvider.class );
        supportedTypes.add( IItemPropertySource.class );
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.AppliesToType} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected AppliesToTypeItemProvider appliesToTypeItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.AppliesToType}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createAppliesToTypeAdapter() {
        if( appliesToTypeItemProvider == null ) {
            appliesToTypeItemProvider = new AppliesToTypeItemProvider( this );
        }

        return appliesToTypeItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.DependsOnType} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected DependsOnTypeItemProvider dependsOnTypeItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.DependsOnType}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createDependsOnTypeAdapter() {
        if( dependsOnTypeItemProvider == null ) {
            dependsOnTypeItemProvider = new DependsOnTypeItemProvider( this );
        }

        return dependsOnTypeItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.DocumentRoot} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected DocumentRootItemProvider documentRootItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.DocumentRoot}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createDocumentRootAdapter() {
        if( documentRootItemProvider == null ) {
            documentRootItemProvider = new DocumentRootItemProvider( this );
        }

        return documentRootItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.ServiceType} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ServiceTypeItemProvider serviceTypeItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.ServiceType}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createServiceTypeAdapter() {
        if( serviceTypeItemProvider == null ) {
            serviceTypeItemProvider = new ServiceTypeItemProvider( this );
        }

        return serviceTypeItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TAbbreviation} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TAbbreviationItemProvider tAbbreviationItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TAbbreviation}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTAbbreviationAdapter() {
        if( tAbbreviationItemProvider == null ) {
            tAbbreviationItemProvider = new TAbbreviationItemProvider( this );
        }

        return tAbbreviationItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TAbbreviations} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TAbbreviationsItemProvider tAbbreviationsItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TAbbreviations}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTAbbreviationsAdapter() {
        if( tAbbreviationsItemProvider == null ) {
            tAbbreviationsItemProvider = new TAbbreviationsItemProvider( this );
        }

        return tAbbreviationsItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TAbstractLNClass} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TAbstractLNClassItemProvider tAbstractLNClassItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TAbstractLNClass}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTAbstractLNClassAdapter() {
        if( tAbstractLNClassItemProvider == null ) {
            tAbstractLNClassItemProvider = new TAbstractLNClassItemProvider( this );
        }

        return tAbstractLNClassItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TApplicableServiceNS} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TApplicableServiceNSItemProvider tApplicableServiceNSItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TApplicableServiceNS}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTApplicableServiceNSAdapter() {
        if( tApplicableServiceNSItemProvider == null ) {
            tApplicableServiceNSItemProvider = new TApplicableServiceNSItemProvider( this );
        }

        return tApplicableServiceNSItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TApplicableServices} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TApplicableServicesItemProvider tApplicableServicesItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TApplicableServices}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTApplicableServicesAdapter() {
        if( tApplicableServicesItemProvider == null ) {
            tApplicableServicesItemProvider = new TApplicableServicesItemProvider( this );
        }

        return tApplicableServicesItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TBasicType} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TBasicTypeItemProvider tBasicTypeItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TBasicType}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTBasicTypeAdapter() {
        if( tBasicTypeItemProvider == null ) {
            tBasicTypeItemProvider = new TBasicTypeItemProvider( this );
        }

        return tBasicTypeItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TBasicTypes} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TBasicTypesItemProvider tBasicTypesItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TBasicTypes}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTBasicTypesAdapter() {
        if( tBasicTypesItemProvider == null ) {
            tBasicTypesItemProvider = new TBasicTypesItemProvider( this );
        }

        return tBasicTypesItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TCDC} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TCDCItemProvider tcdcItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TCDC}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTCDCAdapter() {
        if( tcdcItemProvider == null ) {
            tcdcItemProvider = new TCDCItemProvider( this );
        }

        return tcdcItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TCDCs} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TCDCsItemProvider tcdCsItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TCDCs}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTCDCsAdapter() {
        if( tcdCsItemProvider == null ) {
            tcdCsItemProvider = new TCDCsItemProvider( this );
        }

        return tcdCsItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TChanges} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TChangesItemProvider tChangesItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TChanges}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTChangesAdapter() {
        if( tChangesItemProvider == null ) {
            tChangesItemProvider = new TChangesItemProvider( this );
        }

        return tChangesItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TConstructedAttribute} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TConstructedAttributeItemProvider tConstructedAttributeItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TConstructedAttribute}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTConstructedAttributeAdapter() {
        if( tConstructedAttributeItemProvider == null ) {
            tConstructedAttributeItemProvider = new TConstructedAttributeItemProvider( this );
        }

        return tConstructedAttributeItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TConstructedAttributes} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TConstructedAttributesItemProvider tConstructedAttributesItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TConstructedAttributes}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTConstructedAttributesAdapter() {
        if( tConstructedAttributesItemProvider == null ) {
            tConstructedAttributesItemProvider = new TConstructedAttributesItemProvider( this );
        }

        return tConstructedAttributesItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TCopyrighted} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TCopyrightedItemProvider tCopyrightedItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TCopyrighted}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTCopyrightedAdapter() {
        if( tCopyrightedItemProvider == null ) {
            tCopyrightedItemProvider = new TCopyrightedItemProvider( this );
        }

        return tCopyrightedItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TCopyrightNotice} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TCopyrightNoticeItemProvider tCopyrightNoticeItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TCopyrightNotice}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTCopyrightNoticeAdapter() {
        if( tCopyrightNoticeItemProvider == null ) {
            tCopyrightNoticeItemProvider = new TCopyrightNoticeItemProvider( this );
        }

        return tCopyrightNoticeItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TDataAttribute} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TDataAttributeItemProvider tDataAttributeItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TDataAttribute}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTDataAttributeAdapter() {
        if( tDataAttributeItemProvider == null ) {
            tDataAttributeItemProvider = new TDataAttributeItemProvider( this );
        }

        return tDataAttributeItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TDataObject} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TDataObjectItemProvider tDataObjectItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TDataObject}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTDataObjectAdapter() {
        if( tDataObjectItemProvider == null ) {
            tDataObjectItemProvider = new TDataObjectItemProvider( this );
        }

        return tDataObjectItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TDataSetMemberOf} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TDataSetMemberOfItemProvider tDataSetMemberOfItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TDataSetMemberOf}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTDataSetMemberOfAdapter() {
        if( tDataSetMemberOfItemProvider == null ) {
            tDataSetMemberOfItemProvider = new TDataSetMemberOfItemProvider( this );
        }

        return tDataSetMemberOfItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TDoc} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TDocItemProvider tDocItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TDoc}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTDocAdapter() {
        if( tDocItemProvider == null ) {
            tDocItemProvider = new TDocItemProvider( this );
        }

        return tDocItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TDocumentedClass} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TDocumentedClassItemProvider tDocumentedClassItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TDocumentedClass}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTDocumentedClassAdapter() {
        if( tDocumentedClassItemProvider == null ) {
            tDocumentedClassItemProvider = new TDocumentedClassItemProvider( this );
        }

        return tDocumentedClassItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TEnumeration} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TEnumerationItemProvider tEnumerationItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TEnumeration}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTEnumerationAdapter() {
        if( tEnumerationItemProvider == null ) {
            tEnumerationItemProvider = new TEnumerationItemProvider( this );
        }

        return tEnumerationItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TEnumerations} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TEnumerationsItemProvider tEnumerationsItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TEnumerations}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTEnumerationsAdapter() {
        if( tEnumerationsItemProvider == null ) {
            tEnumerationsItemProvider = new TEnumerationsItemProvider( this );
        }

        return tEnumerationsItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TFunctionalConstraint} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TFunctionalConstraintItemProvider tFunctionalConstraintItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TFunctionalConstraint}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTFunctionalConstraintAdapter() {
        if( tFunctionalConstraintItemProvider == null ) {
            tFunctionalConstraintItemProvider = new TFunctionalConstraintItemProvider( this );
        }

        return tFunctionalConstraintItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TFunctionalConstraints} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TFunctionalConstraintsItemProvider tFunctionalConstraintsItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TFunctionalConstraints}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTFunctionalConstraintsAdapter() {
        if( tFunctionalConstraintsItemProvider == null ) {
            tFunctionalConstraintsItemProvider = new TFunctionalConstraintsItemProvider( this );
        }

        return tFunctionalConstraintsItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TLicense} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TLicenseItemProvider tLicenseItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TLicense}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTLicenseAdapter() {
        if( tLicenseItemProvider == null ) {
            tLicenseItemProvider = new TLicenseItemProvider( this );
        }

        return tLicenseItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TLiteral} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TLiteralItemProvider tLiteralItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TLiteral}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTLiteralAdapter() {
        if( tLiteralItemProvider == null ) {
            tLiteralItemProvider = new TLiteralItemProvider( this );
        }

        return tLiteralItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TLNClass} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TLNClassItemProvider tlnClassItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TLNClass}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTLNClassAdapter() {
        if( tlnClassItemProvider == null ) {
            tlnClassItemProvider = new TLNClassItemProvider( this );
        }

        return tlnClassItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TLNClasses} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TLNClassesItemProvider tlnClassesItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TLNClasses}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTLNClassesAdapter() {
        if( tlnClassesItemProvider == null ) {
            tlnClassesItemProvider = new TLNClassesItemProvider( this );
        }

        return tlnClassesItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TNotice} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TNoticeItemProvider tNoticeItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TNotice}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTNoticeAdapter() {
        if( tNoticeItemProvider == null ) {
            tNoticeItemProvider = new TNoticeItemProvider( this );
        }

        return tNoticeItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TNS} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TNSItemProvider tnsItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TNS}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTNSAdapter() {
        if( tnsItemProvider == null ) {
            tnsItemProvider = new TNSItemProvider( this );
        }

        return tnsItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TNSDoc} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TNSDocItemProvider tnsDocItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TNSDoc}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTNSDocAdapter() {
        if( tnsDocItemProvider == null ) {
            tnsDocItemProvider = new TNSDocItemProvider( this );
        }

        return tnsDocItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TPresenceCondition} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TPresenceConditionItemProvider tPresenceConditionItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TPresenceCondition}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTPresenceConditionAdapter() {
        if( tPresenceConditionItemProvider == null ) {
            tPresenceConditionItemProvider = new TPresenceConditionItemProvider( this );
        }

        return tPresenceConditionItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TPresenceConditions} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TPresenceConditionsItemProvider tPresenceConditionsItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TPresenceConditions}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTPresenceConditionsAdapter() {
        if( tPresenceConditionsItemProvider == null ) {
            tPresenceConditionsItemProvider = new TPresenceConditionsItemProvider( this );
        }

        return tPresenceConditionsItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TServiceCDC} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TServiceCDCItemProvider tServiceCDCItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TServiceCDC}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTServiceCDCAdapter() {
        if( tServiceCDCItemProvider == null ) {
            tServiceCDCItemProvider = new TServiceCDCItemProvider( this );
        }

        return tServiceCDCItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TServiceCDCs} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TServiceCDCsItemProvider tServiceCDCsItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TServiceCDCs}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTServiceCDCsAdapter() {
        if( tServiceCDCsItemProvider == null ) {
            tServiceCDCsItemProvider = new TServiceCDCsItemProvider( this );
        }

        return tServiceCDCsItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TServiceConstructedAttribute} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TServiceConstructedAttributeItemProvider tServiceConstructedAttributeItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TServiceConstructedAttribute}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTServiceConstructedAttributeAdapter() {
        if( tServiceConstructedAttributeItemProvider == null ) {
            tServiceConstructedAttributeItemProvider = new TServiceConstructedAttributeItemProvider( this );
        }

        return tServiceConstructedAttributeItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TServiceConstructedAttributes} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TServiceConstructedAttributesItemProvider tServiceConstructedAttributesItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TServiceConstructedAttributes}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTServiceConstructedAttributesAdapter() {
        if( tServiceConstructedAttributesItemProvider == null ) {
            tServiceConstructedAttributesItemProvider = new TServiceConstructedAttributesItemProvider( this );
        }

        return tServiceConstructedAttributesItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TServiceDataAttribute} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TServiceDataAttributeItemProvider tServiceDataAttributeItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TServiceDataAttribute}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTServiceDataAttributeAdapter() {
        if( tServiceDataAttributeItemProvider == null ) {
            tServiceDataAttributeItemProvider = new TServiceDataAttributeItemProvider( this );
        }

        return tServiceDataAttributeItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TServiceNS} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TServiceNSItemProvider tServiceNSItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TServiceNS}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTServiceNSAdapter() {
        if( tServiceNSItemProvider == null ) {
            tServiceNSItemProvider = new TServiceNSItemProvider( this );
        }

        return tServiceNSItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TServiceNsUsage} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TServiceNsUsageItemProvider tServiceNsUsageItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TServiceNsUsage}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTServiceNsUsageAdapter() {
        if( tServiceNsUsageItemProvider == null ) {
            tServiceNsUsageItemProvider = new TServiceNsUsageItemProvider( this );
        }

        return tServiceNsUsageItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TServiceParameter} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TServiceParameterItemProvider tServiceParameterItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TServiceParameter}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTServiceParameterAdapter() {
        if( tServiceParameterItemProvider == null ) {
            tServiceParameterItemProvider = new TServiceParameterItemProvider( this );
        }

        return tServiceParameterItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TServiceTypeRealization} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TServiceTypeRealizationItemProvider tServiceTypeRealizationItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TServiceTypeRealization}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTServiceTypeRealizationAdapter() {
        if( tServiceTypeRealizationItemProvider == null ) {
            tServiceTypeRealizationItemProvider = new TServiceTypeRealizationItemProvider( this );
        }

        return tServiceTypeRealizationItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TServiceTypeRealizations} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TServiceTypeRealizationsItemProvider tServiceTypeRealizationsItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TServiceTypeRealizations}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTServiceTypeRealizationsAdapter() {
        if( tServiceTypeRealizationsItemProvider == null ) {
            tServiceTypeRealizationsItemProvider = new TServiceTypeRealizationsItemProvider( this );
        }

        return tServiceTypeRealizationsItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TSubDataAttribute} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TSubDataAttributeItemProvider tSubDataAttributeItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TSubDataAttribute}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTSubDataAttributeAdapter() {
        if( tSubDataAttributeItemProvider == null ) {
            tSubDataAttributeItemProvider = new TSubDataAttributeItemProvider( this );
        }

        return tSubDataAttributeItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TSubDataObject} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TSubDataObjectItemProvider tSubDataObjectItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TSubDataObject}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTSubDataObjectAdapter() {
        if( tSubDataObjectItemProvider == null ) {
            tSubDataObjectItemProvider = new TSubDataObjectItemProvider( this );
        }

        return tSubDataObjectItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TTitledClass} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TTitledClassItemProvider tTitledClassItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.nsd.TTitledClass}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTTitledClassAdapter() {
        if( tTitledClassItemProvider == null ) {
            tTitledClassItemProvider = new TTitledClassItemProvider( this );
        }

        return tTitledClassItemProvider;
    }

    /**
     * This returns the root adapter factory that contains this factory.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public ComposeableAdapterFactory getRootAdapterFactory() {
        return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
    }

    /**
     * This sets the composed adapter factory that contains this factory.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public void setParentAdapterFactory( ComposedAdapterFactory parentAdapterFactory ) {
        this.parentAdapterFactory = parentAdapterFactory;
    }

    /**
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public boolean isFactoryForType( Object type ) {
        return supportedTypes.contains( type ) || super.isFactoryForType( type );
    }

    /**
     * This implementation substitutes the factory itself as the key for the adapter.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter adapt( Notifier notifier, Object type ) {
        return super.adapt( notifier, this );
    }

    /**
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Object adapt( Object object, Object type ) {
        if( isFactoryForType( type ) ) {
            Object adapter = super.adapt( object, type );
            if( !( type instanceof Class< ? > ) || ( ( ( Class< ? > ) type ).isInstance( adapter ) ) ) {
                return adapter;
            }
        }

        return null;
    }

    /**
     * This adds a listener.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public void addListener( INotifyChangedListener notifyChangedListener ) {
        changeNotifier.addListener( notifyChangedListener );
    }

    /**
     * This removes a listener.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public void removeListener( INotifyChangedListener notifyChangedListener ) {
        changeNotifier.removeListener( notifyChangedListener );
    }

    /**
     * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public void fireNotifyChanged( Notification notification ) {
        changeNotifier.fireNotifyChanged( notification );

        if( parentAdapterFactory != null ) {
            parentAdapterFactory.fireNotifyChanged( notification );
        }
    }

    /**
     * This disposes all of the item providers created by this factory. 
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public void dispose() {
        if( appliesToTypeItemProvider != null ) appliesToTypeItemProvider.dispose();
        if( dependsOnTypeItemProvider != null ) dependsOnTypeItemProvider.dispose();
        if( documentRootItemProvider != null ) documentRootItemProvider.dispose();
        if( serviceTypeItemProvider != null ) serviceTypeItemProvider.dispose();
        if( tAbbreviationItemProvider != null ) tAbbreviationItemProvider.dispose();
        if( tAbbreviationsItemProvider != null ) tAbbreviationsItemProvider.dispose();
        if( tAbstractLNClassItemProvider != null ) tAbstractLNClassItemProvider.dispose();
        if( tApplicableServiceNSItemProvider != null ) tApplicableServiceNSItemProvider.dispose();
        if( tApplicableServicesItemProvider != null ) tApplicableServicesItemProvider.dispose();
        if( tBasicTypeItemProvider != null ) tBasicTypeItemProvider.dispose();
        if( tBasicTypesItemProvider != null ) tBasicTypesItemProvider.dispose();
        if( tcdcItemProvider != null ) tcdcItemProvider.dispose();
        if( tcdCsItemProvider != null ) tcdCsItemProvider.dispose();
        if( tChangesItemProvider != null ) tChangesItemProvider.dispose();
        if( tConstructedAttributeItemProvider != null ) tConstructedAttributeItemProvider.dispose();
        if( tConstructedAttributesItemProvider != null ) tConstructedAttributesItemProvider.dispose();
        if( tCopyrightedItemProvider != null ) tCopyrightedItemProvider.dispose();
        if( tCopyrightNoticeItemProvider != null ) tCopyrightNoticeItemProvider.dispose();
        if( tDataAttributeItemProvider != null ) tDataAttributeItemProvider.dispose();
        if( tDataObjectItemProvider != null ) tDataObjectItemProvider.dispose();
        if( tDataSetMemberOfItemProvider != null ) tDataSetMemberOfItemProvider.dispose();
        if( tDocItemProvider != null ) tDocItemProvider.dispose();
        if( tDocumentedClassItemProvider != null ) tDocumentedClassItemProvider.dispose();
        if( tEnumerationItemProvider != null ) tEnumerationItemProvider.dispose();
        if( tEnumerationsItemProvider != null ) tEnumerationsItemProvider.dispose();
        if( tFunctionalConstraintItemProvider != null ) tFunctionalConstraintItemProvider.dispose();
        if( tFunctionalConstraintsItemProvider != null ) tFunctionalConstraintsItemProvider.dispose();
        if( tLicenseItemProvider != null ) tLicenseItemProvider.dispose();
        if( tLiteralItemProvider != null ) tLiteralItemProvider.dispose();
        if( tlnClassItemProvider != null ) tlnClassItemProvider.dispose();
        if( tlnClassesItemProvider != null ) tlnClassesItemProvider.dispose();
        if( tNoticeItemProvider != null ) tNoticeItemProvider.dispose();
        if( tnsItemProvider != null ) tnsItemProvider.dispose();
        if( tnsDocItemProvider != null ) tnsDocItemProvider.dispose();
        if( tPresenceConditionItemProvider != null ) tPresenceConditionItemProvider.dispose();
        if( tPresenceConditionsItemProvider != null ) tPresenceConditionsItemProvider.dispose();
        if( tServiceCDCItemProvider != null ) tServiceCDCItemProvider.dispose();
        if( tServiceCDCsItemProvider != null ) tServiceCDCsItemProvider.dispose();
        if( tServiceConstructedAttributeItemProvider != null ) tServiceConstructedAttributeItemProvider.dispose();
        if( tServiceConstructedAttributesItemProvider != null ) tServiceConstructedAttributesItemProvider.dispose();
        if( tServiceDataAttributeItemProvider != null ) tServiceDataAttributeItemProvider.dispose();
        if( tServiceNSItemProvider != null ) tServiceNSItemProvider.dispose();
        if( tServiceNsUsageItemProvider != null ) tServiceNsUsageItemProvider.dispose();
        if( tServiceParameterItemProvider != null ) tServiceParameterItemProvider.dispose();
        if( tServiceTypeRealizationItemProvider != null ) tServiceTypeRealizationItemProvider.dispose();
        if( tServiceTypeRealizationsItemProvider != null ) tServiceTypeRealizationsItemProvider.dispose();
        if( tSubDataAttributeItemProvider != null ) tSubDataAttributeItemProvider.dispose();
        if( tSubDataObjectItemProvider != null ) tSubDataObjectItemProvider.dispose();
        if( tTitledClassItemProvider != null ) tTitledClassItemProvider.dispose();
    }

}
